MealRater.WebMVC/Controllers/MealController.cs
using MealRater.Models;
using MealRater.Services;
using Microsoft.AspNet.Identity;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace MealRater.WebMVC.Controllers.MealVoteControllers
{
    [Authorize]
    public class MealController : Controller
    {
        // GET: MealVoteApp
        public ActionResult Index()
        {
            var service = CreateMealService();
            var model = service.GetMeals();
            return View(model);
        }

        [Authorize(Roles = "Admin")]
        public ActionResult Create()
        {
            return View();
        }

        [Authorize(Roles = "Admin")]
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create(MealCreate model)
        {
            if(!ModelState.IsValid) return View(model);

            var service = CreateMealService();

            if (service.CreateMeal(model))
            {
               TempData["SaveResult"] = "Your meal was created.";
                return RedirectToAction("Index");
            };
            ModelState.AddModelError("", "Error when attempting to create meal.");
            return View(model);
        }

        private MealService CreateMealService()
        {
            var service = new MealService();
            return service;
        }

        public ActionResult Details(int id)
        {
            var svc = CreateMealService();
            var model = svc.GetMealById(id);

            return View(model);
        }

        public ActionResult Edit(int id)
        {
            var service = CreateMealService();
            var detail = service.GetMealById(id);
            var model =
                new MealEdit
                {
                    MealId = detail.MealId,
                    MealName = detail.MealName,
                    MealDescription = detail.MealDescription
                };
            return View(model);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit(int id, MealEdit model)
        {
            if (!ModelState.IsValid) return View(model);

            if (model.MealId != id)
            {
                ModelState.AddModelError("", "Id Mismatch");
                return View(model);
            }

            var service = CreateMealService();

            if (service.UpdateMeal(model))
            {
                TempData["SaveResult"] = "Your meal was updated.";
                return RedirectToAction("Index");
            }

            ModelState.AddModelError("", "Your meal could not be updated.");
            return View(model);
        }

        [ActionName("Delete")]
        public ActionResult Delete(int id)
        {
            var svc = CreateMealService();
            var model = svc.GetMealById(id);

            return View(model);
        }

        [HttpPost]
        [ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteMeal(int id)
        {
            var service = CreateMealService();

            service.DeleteMeal(id);

            TempData["SaveResult"] = "Your meal was deleted";

            return RedirectToAction("Index");
        }


    }
}

MealRater.WebMVC/Controllers/MealVoteController.cs
using MealRater.Models;
using MealRater.Services;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using MealRater.Data;
using System.Web.Mvc;
using Microsoft.AspNet.Identity;

namespace MealRater.WebMVC.Controllers
{
    [Authorize]
    public class MealVoteController : Controller
    {
        //Get
        public ActionResult Index()
        {
            bool isAdmin = false ;
            if (User.IsInRole("Admin"))
            {
                isAdmin = true;
            }
            
            var service = CreateVoteService();
            var model = service.GetVotes(isAdmin);
            return View(model);
        }

        public ActionResult Create()
        {
            var service = new MealService();
            ViewBag.MealId = new SelectList(service.GetMeals(), "MealID", "MealName");
            return View();
        }

        //Post
        [HttpPost, ValidateAntiForgeryToken]
        public ActionResult Create(VoteCreate model)
        {
            if (!ModelState.IsValid) return View(model);
            var service = CreateVoteService();
            if (service.CreateVote(model))
            {
                TempData["SaveResult"] = "Your vote was cast.";
                return RedirectToAction("Index");
            };
            ModelState.AddModelError("", "Something went wrong and your vote was not cast!");
            return View(model);
        }

        private VoteService CreateVoteService()
        {
            var userId = Guid.Parse(User.Identity.GetUserId());
            var service = new VoteService(userId);
            return service;
        }

        public ActionResult Details(int id)
        {
            var svc = CreateVoteService();
            var model = svc.GetVoteById(id);
            return View(model);
        }

        public ActionResult Edit(int id)
        {
            var service = CreateMealService();
            var voteService = CreateVoteService();
            var detail = voteService.GetVoteById(id);
            ViewBag.MealID = new SelectList(service.GetMeals(), "MealID", "MealName");
            var model =
                new VoteEdit
                {
                    MealId = detail.MealId,
                    MealScore = detail.MealScore,
                    VoteId = detail.VoteId
                };
            return View(model);
        }

        public ActionResult Delete(int id)
        {
            var svc = CreateVoteService();
            var model = svc.GetVoteById(id);
            return View(model);
        }

        [HttpPost]
        [ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeletePost(int id)
        {
            var service = CreateVoteService();

            service.DeleteVote(id);

            TempData["SaveResult"] = "Your note was deleted";

            return RedirectToAction("Index");
        }



        private MealService CreateMealService()
        {
            var service = new MealService();
            return service;
        }

        [HttpPost, ValidateAntiForgeryToken]
        public ActionResult Edit(int id, VoteEdit model)
        {
            if (!ModelState.IsValid) return View(model);


            var voteService = CreateVoteService();
            var service = CreateMealService();
            ViewBag.MealID = new SelectList(service.GetMeals(), "MealID", "MealName");

            if (model.VoteId != id)
            {
                ModelState.AddModelError("", "Id Mismatch");
                return View(model);
            }


            if (voteService.UpdateVote(model))
            {
                TempData["SaveResult"] = "Your vote was updated.";
                return RedirectToAction("Index");
            }

            ModelState.AddModelError("", "Your vote could not be updated.");
            return View(model);
        }


    }
}

MealRater.WebMVC/Views/Shared/DateTimeOffset.cshtml
@model System.DateTimeOffset?
<span>
    @(Model.HasValue ? Model.Value.LocalDateTime.ToString("G") : "-")
</span>

MealRater.WebMVC/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - Meal Rater</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
    <script async src="//pagead2.googlesyndication.com/pagead/js/adsbygoogle.js"></script>
    <script>
  (adsbygoogle = window.adsbygoogle || []).push({
    google_ad_client: "ca-pub-6675246899752519",
    enable_page_level_ads: true
  });
    </script>
</head>
<body>
    <nav class="navbar navbar-expand-lg navbar-dark fixed-top bg-primary">
        <div class="container">
            <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarColor01" aria-controls="navbarColor01" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
            @Html.ActionLink("Home", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })
            <div class="navbar-collapse collapse" id="navbarColor01">

                <ul class="nav navbar-nav mr-auto">
                    <li class="nav-item">@Html.ActionLink("About", "About", "Home", null, new { @class = "nav-link" })</li>
                    <li class="nav-item">@Html.ActionLink("Contact", "Contact", "Home", null, new { @class = "nav-link" })</li>
                    @if (User.Identity.IsAuthenticated)
                    {
                        <li>@Html.ActionLink("Meals", "Index", "Meal", null, new { @class = "nav-link" })</li>
                        <li>@Html.ActionLink("Votes", "Index", "MealVote", null, new { @class = "nav-link" })</li>
                    }
                </ul>
                @Html.Partial("_LoginPartial")
            </div>
        </div>
    </nav>

    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - Meal Rater</p>
        </footer>
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>